###
GET http://localhost:8000/products

###
POST http://localhost:8000/products/create
Content-Type: application/json

{
    "name": "Produto 1",
    "price": 10.1
}

###
POST http://localhost:8000/products/create
Content-Type: application/json

{
    "name": "Produto 2",
    "price": 20.2
}

###
POST http://localhost:8000/products/d7edfc6e-5518-4bc9-9067-561e1c8b6bcb/buy
Content-Type: application/json

{
    "amount":100
}

###
POST http://localhost:8000/products/d7edfc6e-5518-4bc9-9067-561e1c8b6bcb/sell
Content-Type: application/json

{
    "amount":25
}